name: ci
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [22, 24, 26]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - run: pnpm ci

      - run: pnpm build

      - name: test templates
        run: |
          mkdir tests && cd tests
          node ../dist/index.js vue-vite --template vue-vite
          node ../dist/index.js vue-rspack --template vue-rspack
          node ../dist/index.js react-vite --template react-vite
          node ../dist/index.js react-rspack --template react-rspack
          pnpm -r install
          pnpm -r build
