name: pkg-pr-new
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version

      - run: pnpm ci

      - run: pnpm build

      - name: examples
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            const dirs = fs.readdirSync('templates').filter(name => !name.startsWith('_'));
            execSync('mkdir examples && cd examples', { stdio: 'inherit' });
            dirs.forEach(name => {
              execSync(`node ../dist/index.js ${name} --template ${name}`, { stdio: 'inherit', cwd: 'examples' });
            });

      - run: pnpm dlx pkg-pr-new publish --bin --packageManager=npm,pnpm,bun --template './examples/*' --previewVersion
